title: Font Size Tweak
description: Change supported Windows 10 and Windows 11 system font sizes without display scaling.
url: https://uxillary.github.io
baseurl: /font-size-tweak
permalink: pretty
include:
  - robots.txt
exclude:
  - README.md
